# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r



language: r
cache: packages
sudo: false
install:
  - Rscript -e "if (!require('devtools')) install.packages('devtools')"
  - Rscript -e "devtools::install_deps(dep = TRUE)"
  - Rscript -e "devtools::install_github('jimhester/covr')"
after_success:
    - Rscript -e 'covr::codecov()'
